stu = open("f101.txt")
print(stu.read())
stu.close()
stu = open("f101.txt",'w')
stu.write("my name is arish ray.")
stu.close()
stu = open("f101.txt",'a')
stu.write("my age is 10.")
stu.close()